version: '3.8'

services:

  # Laravel App 1
  app1:
    image: myhong00/nhatro:latest
    container_name: app1b
    ports:
      - "8001:8000"
    volumes:
      - .:/app                     # Code
      - ./storage:/app/storage     # Logs, cache persist
      - ./public/build:/app/public/build  # Vite build persist
      - .env:/app/.env             # Env config
    depends_on:
      - db

  # Laravel App 2
  app2:
    image: myhong00/nhatro:latest
    container_name: app2
    ports:
      - "8002:8000"
    volumes:
      - .:/app
      - ./storage:/app/storage
      - ./public/build:/app/public/build
      - .env:/app/.env
    depends_on:
      - db

  # Nginx reverse proxy
  web:
    image: nginx:latest
    container_name: nginx
    ports:
      - "8000:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app1
      - app2

  # MySQL Database
  db:
    image: mysql:8
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: nhatro
    ports:
      - "3309:3306"
    volumes:
      - db_data:/var/lib/mysql  # Persist DB

volumes:
  db_data: