upstream laravel_app {
    least_conn;
    server app1:9000;
    server app2:9000;
}

server {
    listen 80;
    server_name localhost;

    root /var/www/html/public;
    index index.php index.html;

    # xử lý request
    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    # xử lý PHP
    location ~ \.php$ {
        include fastcgi_params;
        fastcgi_pass laravel_app;
        fastcgi_index index.php;
        fastcgi_param SCRIPT_FILENAME /var/www/html/public$fastcgi_script_name;
    }

    # chặn file nhạy cảm
    location ~ /\.ht {
        deny all;
    }
}